# Usa una base con R y soporte para Shiny
FROM rocker/r-ver:4.3.1

# Instalar dependencias necesarias para la base de datos y Shiny
RUN apt-get update && apt-get install -y \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar paquetes de R necesarios
RUN R -e "install.packages(c('shiny', 'DBI', 'RPostgres'), repos = 'http://cran.rstudio.com/')"

# Configurar el directorio de trabajo y copiar la aplicación
WORKDIR /app
COPY . /app

# Exponer el puerto de Shiny
EXPOSE 3838

# Comando para iniciar la aplicación Shiny
CMD ["R", "-e", "shiny::runApp('/app', host = '0.0.0.0', port = 3838)"]