triggers:
- description: null
  envs: []
  last_enabled_at: 2024-11-16 10:03:29.636659
  name: refresh_heart_data
  pipeline_uuid: heart_failure_pipeline
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    landing_time_enabled: false
    timeout: '3500'
  sla: null
  start_time: 2024-11-16 10:04:00
  status: active
  token: d6082592e19141ac9a8d02f04fe1515e
  variables: {}
